### ISSUE TITLE
Cannot name Factory property as "modelName"

### ISSUE THREAD

**Issue by LiaoJimmy** [miragejs/miragejs#1113]
## Example Environment
https://stackblitz.com/edit/vitejs-vite-valihw?file=src%2FMirage.ts

## Scenario
- Create a scooter modal
- Create a scooter factory with property: `modelName`
- Create a scooter seed

### Expected Result
- Get scooter list

### Actual Result
Get mirage error
```
miragejs.js?v=9692364e:9061 Uncaught TypeError: Cannot read properties of undefined (reading 'find')
    at Child.isNew (miragejs.js?v=9692364e:9061:52)
    at Child.save (miragejs.js?v=9692364e:8976:14)
    at Schema.create (miragejs.js?v=9692364e:11021:34)
    at Object.create (miragejs.js?v=9692364e:10971:31)
    at Server.create (miragejs.js?v=9692364e:12031:34)
    at Server.createList (miragejs.js?v=9692364e:12094:29)
    at Object.seeds [as default] (Mirage.ts:22:14)
    at Server.config (miragejs.js?v=9692364e:11804:31)
    at new Server (miragejs.js?v=9692364e:11714:10)
    at startMirage (Mirage.ts:4:3)
 ```

## Note
If you rename `modelName` to `modelName123`, it's working correctly.

## Screenshot
![mirage](https://github.com/user-attachments/assets/8744bad0-3ee0-441f-8571-dc8f8bd0bffd)

**Comment by AhmedKhaled590** [comment]
Hi, Can u please assign me to work on this issue?

**Comment by IanVS** [comment]
@AhmedKhaled590 feel free to give it a shot!
